import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "fishpond@EA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {

  return children
  // return (
  //   <html lang="en">
  //     <body>
  //       {children}
  //     </body>
  //   </html>
  // );
}
