/**
 * @tips: this file is generated by @polymita. do not modified this file
 */
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import { RouterProvider, createBrowserRouter } from "react-router-dom";

import Root from "./page";
import Main from "./main/page";
import MainXxxx from "./main/xxxx/page";
import Test from "./test/page";

function RootApplication({ location }) {
  const router = createBrowserRouter([
    {
      path: "/",
      element: <Root />,
      children: [
        {
          path: "/main",
          element: <Main />,
          children: [
            {
              path: "/main/xxxx",
              element: <MainXxxx />,
              children: [],
            },
          ],
        },
        {
          path: "/test",
          element: <Test />,
          children: [],
        },
      ],
    },
  ]);

  return <RouterProvider router={router} />;
}

render(RootApplication);

function render(f) {
  let ele = React.createElement(f);
  const app = ReactDOM.createRoot(document.getElementById("app"));
  app.render(ele);
}
