import type { Metadata } from "next";
import './globals.css'
import ClientLayout from "./clientLayout";

export const metadata: Metadata = {
  title: "fishpond@EA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClientLayout>{children}</ClientLayout>
  );
}
