/**
 * @tips: this file is generated by tarat. do not modified this file
 */
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import { Routes, Route, BrowserRouter } from "react-router-dom";

import Layout from "/Users/zhouyunge/Documents/fishpond-desktop-workspace/packages/fishpond-components/packages/rss-sources/app/layout";

import Main from "/Users/zhouyunge/Documents/fishpond-desktop-workspace/packages/fishpond-components/packages/rss-sources/app/main/page";

function RootApplication({ location }) {
  const router = (
    <BrowserRouter>
      <Layout>
        <Routes>
          <Route path="/main" element={<Main />}></Route>
        </Routes>
      </Layout>
    </BrowserRouter>
  );

  return <>{router}</>;
}

render(RootApplication);

function render(f) {
  let ele = React.createElement(f);
  const app = ReactDOM.createRoot(document.getElementById("app"));
  app.render(ele);
}
