/**
 * @tips: this file is generated by @polymita. do not modified this file
 */
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import {
  RouterProvider,
  createBrowserRouter,
  createHashRouter,
} from "react-router-dom";

import {
  getConfig,
  createModulesContext,
  getModulesContext,
  getDynamicRoutes,
} from "@polymita/next-connect";

import RootLayout from "./layout";
import Sources from "./sources/page";

function RootApplication({ location }) {
  const routes = [
    {
      path: "/",
      element: <RootLayout />,
      children: [
        {
          path: "/sources",
          element: null,
          children: [
            {
              element: <Sources />,
              index: true,
            },
          ],
        },
      ],
    },
  ];
  const dynamicRoutes = getDynamicRoutes();
  if (dynamicRoutes.length) {
    routes.push(...dynamicRoutes);
  }
  const router = createBrowserRouter(routes);

  return <RouterProvider router={router} />;
}

render(RootApplication);

function render(f) {
  let ele = React.createElement(f);
  const app = ReactDOM.createRoot(document.getElementById("app"));
  app.render(ele);
}
