
//
// @@tarat generated file
// provide by @tarat
// warning: auto generated by tarat.do not modifed this file
//
import d from '@polymita/message-timeline/dist/drivers/writeMessage'
Object.assign(d, { __tarat_compose__: true })
export { default } from '@polymita/message-timeline/dist/drivers/writeMessage'
