import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import LayoutWrap from "./layoutWrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "fishpond@EA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrap>
          {children}
        </LayoutWrap>
      </body>
    </html>
  );
}
